# Generated by Django 5.1.5 on 2025-01-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='vehicles',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], default='Car', max_length=20),
        ),
    ]
